export const defaultStore = {
  featured: {},
  detail: {},
  movie: {
    trending: [],
    popular: [],
    top_rated: [],
    upcoming: [],
    now_playing: [],
    cast: [],
    like: [],
    videos: [],
    images: [],
  },
  tv: {
    trending: [],
    popular: [],
    top_rated: [],
    on_the_air: [],
    airing_today: [],
    cast: [],
    like: [],
    videos: [],
    images: [],
  },
  search: {},
};
