export const Actions = {
  FETCH_DATA_SAGA: "FETCH_DATA_SAGA",
  REQUEST_DATA_FETCH: "REQUEST_DATA_FETCH",
  REQUEST_LOAD_HOME: "REQUEST_LOAD_HOME",
  REQUEST_LOAD_MOVIE: "REQUEST_LOAD_MOVIE",
  REQUEST_LOAD_TV: "REQUEST_LOAD_TV",
  REQUEST_LOAD_DETAIL: "REQUEST_LOAD_DETAIL",
};
